name: ChatAssets
version: 0.2
description: This plugin collects several mainly used chat related features.
author: GitHub/RcExtract
main: me.rcextract.chatassets.Main
softdepend: [ActionBarAPI]
commands:
    chatassets:
        usage: /<command>
        description: Main command of ChatAssets.
    msg:
        usage: /<command>
        description: Message a player privately.
    reply:
        usage: /<command>
        description: Reply to a player.
permissions:
    chatassets.*:
        default: false
        children:
            chatassets.main: true
            chatassets.help: true
            chatassets.reload: true
            chatassets.anticurse.bypass: true
            chatassets.anticasespam.bypass: true
            chatassets.cooldowner.bypass: true
            chatassets.messageshortener.add: true
            chatassets.messageshortener.remove: true
            chatassets.messageshortener.use: true
            chatassets.antiadvertising.bypass: true
            chatassets.basic.chat: true
            chatassets.basic.automodify.bypass: true
            chatassets.msg: true
            chatassets.msg.reply: true
            chatassets.loghandler.joinmessage.receive: true
            chatassets.loghandler.motd.receive: true
            chatassets.loghandler.quitmessage.receive: true
    chatassets.main:
        default: true
    chatassets.help:
        default: true
    chatassets.reload:
        default: op
    chatassets.anticurse.bypass:
        default: false
    chatassets.anticasespam.bypass:
        default: false
    chatassets.cooldowner.bypass:
        default: op
    chatassets.messageshortener.add:
        default: op
    chatassets.messageshortener.remove:
        default: op
    chatassets.messageshortener.use:
        default: true
    chatassets.antiadvertising.bypass:
        default: false
    chatassets.basic.chat:
        default: true
    chatassets.basic.automodify.bypass:
        default: op
    chatassets.msg:
        default: true
    chatassets.msg.reply:
        default: true
    chatassets.loghandler.joinmessage.receive:
        default: true
    chatassets.loghandler.motd.receive:
        default: true
    chatassets.loghandler.quitmessage.receive:
        default: true
    chatassets.loghandler.joinmessage.view:
        default: true
    chatassets.loghandler.motd.view:
        default: true
    chatassets.loghandler.quitmessage.view:
        default: true
    chatassets.loghandler.joinmessage.set:
        default: op
    chatassets.loghandler.motd.set:
        default: op
    chatassets.loghandler.quitmessage.set:
        default: op